# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=250)),
                ('topic', models.CharField(max_length=250)),
                ('stats', models.CharField(max_length=250)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genque.Report')),
            ],
        ),
    ]
