# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('MCQ', models.BooleanField()),
                ('MCQ_items', models.SmallIntegerField()),
                ('TF', models.BooleanField()),
                ('TF_items', models.SmallIntegerField()),
                ('FINB', models.BooleanField()),
                ('FINB_items', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='statistics',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genque.Generate'),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
